"""empty message

Revision ID: 009d340f8837
Revises: 4940a39dde77
Create Date: 2024-04-16 14:33:50.022706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009d340f8837'
down_revision = '4940a39dde77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('Name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('Lat',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('Long',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('Long',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('Lat',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('Name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
