"""empty message

Revision ID: 51dcaefa7045
Revises: 009d340f8837
Create Date: 2024-04-16 14:45:14.130491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51dcaefa7045'
down_revision = '009d340f8837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_plants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_plants',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.VARCHAR(), nullable=False),
    sa.Column('Lat', sa.FLOAT(), nullable=False),
    sa.Column('Long', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###
